<a href="https://colab.research.google.com/github/gnutan181/pytorch_tutorial/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4



```
`# This is formatted as code`
```

## Creating a Tensor

In [ ]:
a = torch.empty(2,3)
print(a)

tensor([[2.8612e-11, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])


In [ ]:
type(a)

torch.Tensor

In [ ]:
print(torch.zeros(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
print(torch.ones(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
torch.rand(2,3)

tensor([[0.8488, 0.5777, 0.8067],
        [0.4966, 0.7575, 0.7375]])

In [ ]:
torch.rand(2,3)

tensor([[0.2058, 0.6962, 0.4301],
        [0.7498, 0.2087, 0.0131]])

In [ ]:
torch.manual_seed(50)
torch.rand(2,3)

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [ ]:
torch.manual_seed(50)
torch.rand(2,3)

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
print("Using arange", torch.arange(0,90,3))

Using arange tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87])


In [ ]:
print("using linespace",torch.linspace(0,10,5))

using linespace tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [ ]:
# using eye -> identity mattrix
print("using eye ->", torch.eye(5))

using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
torch.full((2,3),5)

tensor([[5, 5, 5],
        [5, 5, 5]])

 Tensor Shapes

In [ ]:
x =torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[    134704289377232,           811389840,                   0],
        [                  0,        498216206336, 7310593858020254331]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [3]:
torch.rand_like(x)

NameError: name 'x' is not defined

Tensor Data Types



In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.1,1,3.0],dtype=torch.int32)

tensor([1, 1, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype  = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


Mathematical operations

1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.4605, 0.4877],
        [0.5927, 0.9634]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# # multiplication
x * 3
# # division
x / 3
# # int division
(x * 100)//3
# # mod
((x * 100)//3)%2
# # power
x**2

tensor([[0.2120, 0.2378],
        [0.3513, 0.9281]])

### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1230, 0.4048, 0.4985],
        [0.9987, 0.6049, 0.5229]])
tensor([[0.6974, 0.2505, 0.3624],
        [0.4621, 0.7145, 0.5058]])


In [ ]:
# add
a + b
# sub
a - b
# # multiply
a * b
# # division
a / b
# # power
a ** b
# # mod
a % b

tensor([[0.1230, 0.1543, 0.1361],
        [0.0745, 0.6049, 0.0171]])

In [4]:
c = torch.tensor([1, -2, 3, -4])

In [5]:
print(torch.abs(c))

tensor([1, 2, 3, 4])


In [6]:
print(torch.neg(c))

tensor([-1,  2, -3,  4])


In [8]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [9]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [10]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [11]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [12]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])