<a href="https://colab.research.google.com/github/gnutan181/pytorch_tutorial/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


In [3]:
a = torch.empty(2,3)
print(a)

tensor([[2.8612e-11, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])


In [4]:
type(a)

torch.Tensor

In [5]:
print(torch.zeros(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
print(torch.ones(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
torch.rand(2,3)

tensor([[0.8488, 0.5777, 0.8067],
        [0.4966, 0.7575, 0.7375]])

In [8]:
torch.rand(2,3)

tensor([[0.2058, 0.6962, 0.4301],
        [0.7498, 0.2087, 0.0131]])

In [11]:
torch.manual_seed(50)
torch.rand(2,3)

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [13]:
torch.manual_seed(50)
torch.rand(2,3)

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [15]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
print("Using arange", torch.arange(0,90,3))

Using arange tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87])


In [26]:
print("using linespace",torch.linspace(0,10,5))

using linespace tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [27]:
# using eye -> identity mattrix
print("using eye ->", torch.eye(5))

using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [28]:
torch.full((2,3),5)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [36]:
x =torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [37]:
torch.empty_like(x)

tensor([[    134704289377232,           811389840,                   0],
        [                  0,        498216206336, 7310593858020254331]])

In [38]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [39]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [40]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [42]:
x.dtype

torch.int64

In [43]:
torch.tensor([1.1,1,3.0],dtype=torch.int32)

tensor([1, 1, 3], dtype=torch.int32)

In [44]:
torch.tensor([1,2,3],dtype  = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)